{{- if and .Values.nats.enabled .Values.nats.configRestore }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "sie-cluster.fullname" . }}-config-store
  namespace: {{ include "sie-cluster.namespace" . }}
  labels:
    {{- include "sie-cluster.router.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 64Mi
{{- end }}
